### ISSUE TITLE
pause + resume + change delay

### ISSUE THREAD

**Issue by mayorovp** [xenohunter/timestore#4]
Библиотека некорректно ведет себя если объект Timeout сначала усыпить, потом разбудить - и наконец сменить ему значение задержки.

Ожидаемое поведение: задержка должна вычисляться относительно момента первого запуска, с учетом промежутка времени сна

Что получается: задержка вычисляется относительно момента последнего пробуждения

**Comment by xenohunter** [comment]
Bug fixed in commit https://github.com/xenohunter/timestore/commit/2f4575dbd70173fcfb36e93219eaceaf43a6f562.

The bug was affecting the Timeout class by setting a wrong delay after pausing and resuming a timeout.
