### ISSUE TITLE
Examples page broken (404s on the js)

### ISSUE THREAD

**Issue by photonstorm** [xenohunter/timestore#6]
Hiya,

The Examples page is currently broken, because you published a new release, but it tries to load this and falls over: `https://cdn.rawgit.com/xenohunter/timestore/master/timestore.1.1.0.js`

**Comment by xenohunter** [comment]
@photonstorm oh, my bad. Thank you very much! Fixed.
I wanted to share that lib with you after adding some features. Glad you've taken a look!

**Comment by photonstorm** [comment]
I was in the process of adding it to the Phaser news site when I saw the Examples was broken :) Figured I'd let you fix it first or it might confuse people!

**Comment by xenohunter** [comment]
@photonstorm that sounds exciting, I really appreciate it!

I was going to add chaining and `.callWith(arg1, arg2, ...)` method to cover `setTimeout(callback, delay, arg1, arg2, ...)` syntax. Now it's time to hurry! I'll commit those features in 2-3 days.
